version: 2.1
jobs:
  react-native-test:
    docker:
      - image: cimg/node:16.15.1

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: ESLint
          command: yarn lint
      - run:
          name: Tests
          command: yarn test

workflows:
  react-native-test:
    jobs:
      - react-native-test