export enum ColorsEnum {
  VIEW_BACKGROUND_COLOR = '#F4F4F4',
  INPUT_BACKGROUND_COLOR = '#FFFFFF',
  INPUT_STROKE_COLOR = '#79747E',
  INDICATIVE_TEXT_COLOR = '#79747E',
  BUSINESS_TEXT_COLOR = '#000000',
  PRIMARY_COLOR_BUTTON = '#E8DEF8',
  SECONDARY_COLOR_BUTTON = '#F8DEDE',
}
